### ISSUE TITLE
Распределитель команд

### ISSUE THREAD

**Issue by Fiarcherry** [DiaLight/EventHelper#4]
В actionbar всех остальных предметов отображаются названия цвета aqua обычного стиля, а распределитель белый и с наклонным шрифтом, должно быть везде одинаково.

В меню создания команды присутствуют не все цвета, например dark_green_team есть, а green_team нет

**Comment by DiaLight** [comment]
Должно было пофикситься в [build-362](https://github.com/DiaLight/EventHelper/releases/tag/build-362)

**Comment by DiaLight** [comment]
Теперь в списке команд для создания явно помечаются команды, что уже созданы и что их нельзя создать еще раз.
![Screenshot_125](https://user-images.githubusercontent.com/5149955/56393194-4cf20500-623c-11e9-8f4c-cc6d00395d15.png)
